// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgreDemo.Data;

#nullable disable

namespace PostgreDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostgreDemo.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            CreatedAt = new DateTime(2024, 1, 30, 15, 3, 43, 629, DateTimeKind.Utc).AddTicks(2025),
                            Description = "A novel about the American Dream during the Roaring Twenties.",
                            Name = "The Great Gatsby",
                            Price = 14.99
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            CreatedAt = new DateTime(2024, 2, 4, 15, 3, 43, 629, DateTimeKind.Utc).AddTicks(2034),
                            Description = "A classic novel addressing racial injustice in the American South.",
                            Name = "To Kill a Mockingbird",
                            Price = 19.989999999999998
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            CreatedAt = new DateTime(2024, 2, 9, 15, 3, 43, 629, DateTimeKind.Utc).AddTicks(2035),
                            Description = "A dystopian novel depicting a totalitarian society.",
                            Name = "1984",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.D. Salinger",
                            CreatedAt = new DateTime(2024, 2, 11, 15, 3, 43, 629, DateTimeKind.Utc).AddTicks(2037),
                            Description = "A coming-of-age novel following the experiences of a teenage boy in New York City.",
                            Name = "The Catcher in the Rye",
                            Price = 16.989999999999998
                        },
                        new
                        {
                            Id = 5,
                            Author = "Jane Austen",
                            CreatedAt = new DateTime(2024, 2, 14, 15, 3, 43, 629, DateTimeKind.Utc).AddTicks(2038),
                            Description = "A classic novel exploring issues of love, reputation, and class.",
                            Name = "Pride and Prejudice",
                            Price = 18.989999999999998
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.R.R. Tolkien",
                            CreatedAt = new DateTime(2024, 2, 17, 15, 3, 43, 629, DateTimeKind.Utc).AddTicks(2039),
                            Description = "A fantasy novel that serves as a prelude to The Lord of the Rings trilogy.",
                            Name = "The Hobbit",
                            Price = 22.989999999999998
                        },
                        new
                        {
                            Id = 7,
                            Author = "Gabriel García Márquez",
                            CreatedAt = new DateTime(2024, 2, 19, 15, 3, 43, 629, DateTimeKind.Utc).AddTicks(2042),
                            Description = "A landmark novel in the magical realism genre, exploring the history of the Buendía family.",
                            Name = "One Hundred Years of Solitude",
                            Price = 20.989999999999998
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.R.R. Tolkien",
                            CreatedAt = new DateTime(2024, 2, 21, 15, 3, 43, 629, DateTimeKind.Utc).AddTicks(2043),
                            Description = "An epic high fantasy trilogy that follows the journey to destroy the One Ring.",
                            Name = "The Lord of the Rings",
                            Price = 29.989999999999998
                        },
                        new
                        {
                            Id = 9,
                            Author = "C.S. Lewis",
                            CreatedAt = new DateTime(2024, 2, 24, 15, 3, 43, 629, DateTimeKind.Utc).AddTicks(2044),
                            Description = "A series of seven high fantasy novels set in the fictional world of Narnia.",
                            Name = "The Chronicles of Narnia",
                            Price = 26.989999999999998
                        },
                        new
                        {
                            Id = 10,
                            Author = "Aldous Huxley",
                            CreatedAt = new DateTime(2024, 2, 26, 15, 3, 43, 629, DateTimeKind.Utc).AddTicks(2046),
                            Description = "A dystopian novel that explores the dangers of a technologically advanced society.",
                            Name = "Brave New World",
                            Price = 17.989999999999998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
